name: build and release project
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      logLevel:
        description: "log level"
        required: true
        default: "warning"
      tags:
        description: "test scenario tags"

jobs:
  buildx:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux]
        arch: [amd64, arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: buildx
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ matrix.os }}/${{ matrix.arch }}
          push: false
          tags: huatuo/huatuo-bamai:latest
      - name: Extract files
        run: |
          tmpdir="huatuo-${{ github.ref_name }}-${{ matrix.os }}-${{ matrix.arch }}"

          docker create --name tmp-container huatuo/huatuo-bamai:latest
          docker cp tmp-container:/home/huatuo-bamai .
          docker rm tmp-container
          mv huatuo-bamai $tmpdir
          cp LICENSE $tmpdir 
          cp README*.md $tmpdir

          tree $tmpdir
          tar zcf ${tmpdir}.tar.gz ${tmpdir} 

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          tag_name: "v${{ github.event.inputs.version }}"
          generate_release_notes: true
          token: ${{ secrets.HUATUO_RELEASE_TOKEN }}
          files: |
            "huatuo-${{ github.ref_name }}-${{ matrix.os }}-${{ matrix.arch }}".tar.gz
