name: build and release project
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      logLevel:
        required: true
        default: "warning"
      tags:
        description: "test scenario tags"

jobs:
  buildx:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux]
        arch: [amd64, arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get current date
        id: date
        run: echo "::set-output name=today::$(date +'%Y-%m-%d_%H-%M')"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ matrix.os }}/${{ matrix.arch }}
          push: false
          tags: huatuo/huatuo-bamai:latest
      - name: Extract files
        run: |
          tmpdir="huatuo-${{ github.ref_name }}-${{ matrix.os }}-${{ matrix.arch }}"
          mkdir -p $tmpdir

          docker create --name tmp-container huatuo/huatuo-bamai:latest
          docker cp tmp-container:/home $tmpdir
          docker rm tmp-container

          tree $tmpdir
          tar zcvf ${tmpdir}.tar.gz ${tmpdir} 
          uname -a 
          ls -l
      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: "huatuo-${{ github.ref_name }}-${{ matrix.os }}-${{ matrix.arch }}".tar.gz
